project:
  type: website
  output-dir: _site

website:
  title: "MakeTables"
  description: "A Python package for creating publication-ready tables"
  navbar:
    left:
      - href: docs/getting-started.ipynb
        text: Getting Started
      - href: docs/ETable.ipynb
        text: Regressions
      - href: docs/DTable.ipynb
        text: Descriptives
      - href: docs/DocxTables.ipynb
        text: Word
      - href: docs/LatexTables.ipynb
        text: LaTeX
      - href: docs/WritingPapers.ipynb
        text: Writing Papers
      - href: docs/SupportedModelClasses.md
        text: Supported Models
      - text: Further Resources
        menu:
          - href: docs/MTable.ipynb
            text: "Custom Tables with MTable"
          - href: docs\TypstTables.ipynb
            text: "Output to Typst"
          - href: docs/pystataIntegration.ipynb
            text: "Stata Integration"
          - href: docs/UsingLabels.ipynb
            text: "Using Variable Labels"
          - href: docs/AddingMethods.ipynb
            text: "Making Packages Compatible"
          - text: "API Reference"
            file: reference/index.qmd


    right:
      - icon: github
        href: https://github.com/py-econometrics/maketables



quartodoc:
  style: pkgdown
  dir: reference
  package: maketables
  sections:
    - title: "Table Classes"
      desc: "Main table creation classes"
      contents:
        - MTable
        - DTable
        - BTable
        - ETable
    - title: "Utilities"
      desc: "Helper functions"
      contents:
        - importdta.get_var_labels
        - importdta.set_var_labels
        - importdta.import_dta
        - importdta.export_dta


format:
  html:
    theme: yeti
    toc: true
    code-copy: true
    code-fold: false
    html-table-processing: none
  
execute:
  freeze: auto

exclude:
  - "introductions.ipynb"
  - ".venv/"
  - "__pycache__/"
  - "mystuff/"
  - "output/"